openapi: 3.0.0
info:
  title: Health API
  version: 1.0.0
  description: API to check application health

paths:
  /health:
    get:
      summary: Check application health
      description: Returns the health status of the application
      responses:
        '200':
          description: Successful health check
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: SUCCESSFULL
                  message:
                    type: string
                    example: Connection Establised
