server:
  port: 8081

spring:
  application:
    name: task-management-system
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Chetan123@#
  jpa:
    hibernate:
      ddl-auto: update