server:
  port: 8081

spring:
  application:
    name: task-management-system
  datasource:
    url: ${APPLICATION_DATASOURCE_LOCAL_URL}
    basePackages: ${DATASOURCE_LOCAL_BASEPACKAGES}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update