server:
  port: 8081

spring:
  application:
    name: task-management-system
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    basePackages: "com.example.task_management_system.repository.postgres.ro"
    username: postgres
    password: Chetan123@#
  jpa:
    hibernate:
      ddl-auto: update